# 1.) Pandas Intro - What is Pandas?
In computer programming, pandas is a software library written for the Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series.


# 2.) Read the data from CSV/Excel/.....

In [97]:
import pandas as pd

In [98]:
### read the data - DataFrame - Pandas doesn't modify the original data file. 
### Without specifying the sheet name - read the first sheet by default. 
df = pd.read_excel("Wusthof.xlsx")

In [99]:
df1 = pd.read_excel("Wusthof.xlsx", sheet_name=0)

In [100]:
df1.head()

,Name,Price,Comments_Volume,Sentiment_Index,Date,Timestamp,Timedelta,Date_Dashed,Date_Dotted
0,Wusthof Classic 8-Inch Chef's Knife,124.97,506,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
1,Wusthof Gourmet 18 Piece Cherry Block Knife Cu...,279.95,27,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
2,"Wusthof Classic Ikon 8-Inch Cook's Knife, Black",120.04,323,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
3,Wusthof 4183-7 Wusthof Classic 7-Inch Santoku ...,104.94,436,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
4,"Wüsthof - 10"" Knife Sharpening Steel with Loop",24.95,364,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0

# 3.) Select A Series/Column From Pandas DataFrame

In [101]:
### Select a single column to read - "Price"
df["Price"].head()

0    124.97
1    279.95
2    120.04
3    104.94
4     24.95
Name: Price, dtype: object

In [102]:
##  Select several columns to read - "Name", "Price", "Sentiment_Index"
df[["Name", "Price", "Sentiment_Index"]].head()

                                                Name   Price  Sentiment_Index
0                Wusthof Classic 8-Inch Chef's Knife  124.97         0.222105
1  Wusthof Gourmet 18 Piece Cherry Block Knife Cu...  279.95         0.222105
2    Wusthof Classic Ikon 8-Inch Cook's Knife, Black  120.04         0.222105
3  Wusthof 4183-7 Wusthof Classic 7-Inch Santoku ...  104.94         0.222105
4     Wüsthof - 10" Knife Sharpening Steel with Loop   24.95         0.222105

In [103]:
#### Another notation to read a single column from a dataset. 
df.Name.head()

0                  Wusthof Classic 8-Inch Chef's Knife
1    Wusthof Gourmet 18 Piece Cherry Block Knife Cu...
2      Wusthof Classic Ikon 8-Inch Cook's Knife, Black
3    Wusthof 4183-7 Wusthof Classic 7-Inch Santoku ...
4       Wüsthof - 10" Knife Sharpening Steel with Loop
Name: Name, dtype: object

# 4.) Check the Columns/Rename Columns /Examine DataFrame Shape

In [104]:
# 1.) get all column names

### Return a list of column names from dataframe
df.columns.tolist()

#### let's check the date column
df["Date"].head()

0    20180518
1    20180518
2    20180518
3    20180518
4    20180518
Name: Date, dtype: int64

In [105]:
# 2.) Check the shape of dataframe: return quantities of rows and columns.

In [106]:
df.shape # Row Num goes first and column num goes second.

(30312, 9)

In [107]:
rows = df.shape[0]
rows

30312

In [108]:
columns = df.shape[1]
columns

9

In [109]:
df.columns

Index(['Name', 'Price', 'Comments_Volume', 'Sentiment_Index', 'Date',
       'Timestamp', 'Timedelta', 'Date_Dashed', 'Date_Dotted'],
      dtype='object')

Wihtout specifying the inplace keyword: True/False, doesn't change the column name in reality by default.

In [110]:
df.rename(index=str, columns={"Comments_Volume":"Comments",
                             "Price":"Jiage"}).head()

,Name,Jiage,Comments,Sentiment_Index,Date,Timestamp,Timedelta,Date_Dashed,Date_Dotted
0,Wusthof Classic 8-Inch Chef's Knife,124.97,506,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
1,Wusthof Gourmet 18 Piece Cherry Block Knife Cu...,279.95,27,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
2,"Wusthof Classic Ikon 8-Inch Cook's Knife, Black",120.04,323,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
3,Wusthof 4183-7 Wusthof Classic 7-Inch Santoku ...,104.94,436,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
4,"Wüsthof - 10"" Knife Sharpening Steel with Loop",24.95,364,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0

In [111]:
df.rename(index=str, columns={"Comments_Volume":"Comments",
                             "Price":"Jiage"}, inplace=True)

In [112]:
### !!!!!!!!!! Notice now: the column names have been modified permanently. 
df.head()

,Name,Jiage,Comments,Sentiment_Index,Date,Timestamp,Timedelta,Date_Dashed,Date_Dotted
0,Wusthof Classic 8-Inch Chef's Knife,124.97,506,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
1,Wusthof Gourmet 18 Piece Cherry Block Knife Cu...,279.95,27,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
2,"Wusthof Classic Ikon 8-Inch Cook's Knife, Black",120.04,323,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
3,Wusthof 4183-7 Wusthof Classic 7-Inch Santoku ...,104.94,436,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
4,"Wüsthof - 10"" Knife Sharpening Steel with Loop",24.95,364,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0

In [113]:
#### Let's restore the names.

In [114]:
df.rename(index=str, columns={"Comments":"Comments_Volume", 
                             "Jiage":"Price"}, inplace=True)

In [115]:
df.head()

,Name,Price,Comments_Volume,Sentiment_Index,Date,Timestamp,Timedelta,Date_Dashed,Date_Dotted
0,Wusthof Classic 8-Inch Chef's Knife,124.97,506,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
1,Wusthof Gourmet 18 Piece Cherry Block Knife Cu...,279.95,27,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
2,"Wusthof Classic Ikon 8-Inch Cook's Knife, Black",120.04,323,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
3,Wusthof 4183-7 Wusthof Classic 7-Inch Santoku ...,104.94,436,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
4,"Wüsthof - 10"" Knife Sharpening Steel with Loop",24.95,364,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0

# 5.) df.head()/ df.tail()

In [116]:
### Downsize our print - only print the first 5 rows. 
df.head()

,Name,Price,Comments_Volume,Sentiment_Index,Date,Timestamp,Timedelta,Date_Dashed,Date_Dotted
0,Wusthof Classic 8-Inch Chef's Knife,124.97,506,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
1,Wusthof Gourmet 18 Piece Cherry Block Knife Cu...,279.95,27,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
2,"Wusthof Classic Ikon 8-Inch Cook's Knife, Black",120.04,323,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
3,Wusthof 4183-7 Wusthof Classic 7-Inch Santoku ...,104.94,436,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
4,"Wüsthof - 10"" Knife Sharpening Steel with Loop",24.95,364,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0

In [117]:
### print specific row number
df.head(8)

,Name,Price,Comments_Volume,Sentiment_Index,Date,Timestamp,Timedelta,Date_Dashed,Date_Dotted
0,Wusthof Classic 8-Inch Chef's Knife,124.97,506,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
1,Wusthof Gourmet 18 Piece Cherry Block Knife Cu...,279.95,27,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
2,"Wusthof Classic Ikon 8-Inch Cook's Knife, Black",120.04,323,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
3,Wusthof 4183-7 Wusthof Classic 7-Inch Santoku ...,104.94,436,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
4,"Wüsthof - 10"" Knife Sharpening Steel with Loop",24.95,364,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
5,"Wusthof Classic Chef's Knife: 6""",59.95,68,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
6,"Wüsthof - Three Piece Cook’s Set - 3 1/2"" Pari...",204,229,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
7,"Wüsthof - Three Piece Cook’s Set - 3 1/2"" Pari...",204,229,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0

In [118]:
#### Only print the last 5 rows 
df.tail()

,Name,Price,Comments_Volume,Sentiment_Index,Date,Timestamp,Timedelta,Date_Dashed,Date_Dotted
30307,Wusthof Pro 9 Inch Cook's Knife,33.95,3,0.392477,20180820,1534723200,20180612,2018-08-20,NaN
30308,Wusthof Personal Care Stainless Steel Toenail ...,39.95,10,0.134536,20180820,1534723200,20180612,2018-08-20,NaN
30309,"Wusthof Pro Bread Knife, 9-Inch",33.95,14,0.347232,20180820,1534723200,20180612,2018-08-20,NaN
30310,Wusthof blade guard 10 carver,11.95,28,0.195775,20180820,1534723200,20180612,2018-08-20,NaN
30311,Wusthof Ikon 6-Inch Utility Knife with Blackwo...,149.95,2,0.200227,20180820,1534723200,20180612,2018-08-20,NaN

In [119]:
#### Specific rows to read from the very last row - 
df.tail(10)

,Name,Price,Comments_Volume,Sentiment_Index,Date,Timestamp,Timedelta,Date_Dashed,Date_Dotted
30302,Wusthof Classic Ikon 7 Inch Fillet Knife,135.00,8,0.368667,20180820,1534723200,20180612,2018-08-20,NaN
30303,Wusthof-Trident Wusthof 4452 3000/ 8000 Grit W...,89.00,21,0.437671,20180820,1534723200,20180612,2018-08-20,NaN
30304,"Wusthof Pro Cimeter Knife, 10-Inch",49.95,21,0.300779,20180820,1534723200,20180612,2018-08-20,NaN
30305,"Wusthof 4163-7/23 Bread Knife, 9"", Silver",102.38,1,0.058471,20180820,1534723200,20180612,2018-08-20,NaN
30306,Wusthof Grand Prix II 8-Inch Hollow-Ground Coo...,129.95,12,0.319660,20180820,1534723200,20180612,2018-08-20,NaN
30307,Wusthof Pro 9 Inch Cook's Knife,33.95,3,0.392477,20180820,1534723200,20180612,2018-08-20,NaN
30308,Wusthof Personal Care Stainless Steel Toenail ...,39.95,10,0.134536,20180820,1534723200,20180612,2018-08-20,NaN
30309,"Wusthof Pro Bread Knife, 9-Inch",33.95,14,0.347232,20180820,1534723200,20180612,2018-08-20,NaN
30310,Wusthof blade guard 10 carver,11.95,28,0.195775,20180820,1534723200,20180612,2018-08-20,NaN
30311,Wusthof Ikon 6-Inch Utility Knife with Blackwo...,149.95,2,0.200227,20180820,1534723200,20180612,2018-08-20,NaN

# 6.) Why sometimes Pandas method ends with () and sometimes not? () /

In [120]:
df.shape ## This is an Attribute so it doesn't end with parenthesis: ().

(30312, 9)

In [121]:
df.head() # : print the head. - This is a function: so it ends withs ().

,Name,Price,Comments_Volume,Sentiment_Index,Date,Timestamp,Timedelta,Date_Dashed,Date_Dotted
0,Wusthof Classic 8-Inch Chef's Knife,124.97,506,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
1,Wusthof Gourmet 18 Piece Cherry Block Knife Cu...,279.95,27,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
2,"Wusthof Classic Ikon 8-Inch Cook's Knife, Black",120.04,323,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
3,Wusthof 4183-7 Wusthof Classic 7-Inch Santoku ...,104.94,436,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
4,"Wüsthof - 10"" Knife Sharpening Steel with Loop",24.95,364,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0

# 7.) Check data types of pandas series/columns

In [122]:
#### "Object" in Pandas Dataframe resembles "str" data type in Python
df.dtypes

Name                object
Price               object
Comments_Volume      int64
Sentiment_Index    float64
Date                 int64
Timestamp            int64
Timedelta            int64
Date_Dashed         object
Date_Dotted        float64
dtype: object

# 8.) Sort values in pandas dataframe - df

In [123]:
### Check the columns
df.columns

Index(['Name', 'Price', 'Comments_Volume', 'Sentiment_Index', 'Date',
       'Timestamp', 'Timedelta', 'Date_Dashed', 'Date_Dotted'],
      dtype='object')

In [124]:
#### Sort the whole dataframe (without specifying inplace arguement - doesn't sort in reality)

In [125]:
df.sort_values("Comments_Volume",ascending=True).head(3)

,Name,Price,Comments_Volume,Sentiment_Index,Date,Timestamp,Timedelta,Date_Dashed,Date_Dotted
12798,Wusthof Ikon 9-inch Cook's Knife Blackwood,249.95,1,0.216667,20180619,1529366400,20180550,2018-06-19,NaN
2240,Wusthof 1000/3000 Grit Fine Whetstone,89.95,1,-0.291667,20180518,1526774400,20180518,2018-05-18,20180520.22
13904,Wusthof Classic Hollow Edge Full Tank 7” Nakir...,105.00,1,0.000000,20180623,1529712000,20180554,2018-06-23,NaN

In [126]:
### Notice it!!!!: the order of indices haven't been actually sorted. 
df.head(3)

,Name,Price,Comments_Volume,Sentiment_Index,Date,Timestamp,Timedelta,Date_Dashed,Date_Dotted
0,Wusthof Classic 8-Inch Chef's Knife,124.97,506,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
1,Wusthof Gourmet 18 Piece Cherry Block Knife Cu...,279.95,27,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0
2,"Wusthof Classic Ikon 8-Inch Cook's Knife, Black",120.04,323,0.222105,20180518,1526601600,20180518,2018-05-18,20180518.0

In [130]:
### Sort inplace now: inplace=True
df.sort_values("Comments_Volume", ascending=True, inplace=True)

In [131]:
#### Look Now: the order of indices have been sorted ascendingly. 

df.head(3)

,Name,Price,Comments_Volume,Sentiment_Index,Date,Timestamp,Timedelta,Date_Dashed,Date_Dotted
12798,Wusthof Ikon 9-inch Cook's Knife Blackwood,249.95,1,0.216667,20180619,1529366400,20180550,2018-06-19,NaN
24794,Wusthof Classic 21-Piece Block Set 8275-2,"1,249.95",1,0.883333,20180801,1533081600,20180593,2018-08-01,NaN
24789,"Wüsthof Classic Ikon Paring Knife - 4½"" - Creme",60.00,1,-0.039167,20180801,1533081600,20180593,2018-08-01,NaN